# Generated by Django 3.0.2 on 2020-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral_name', models.CharField(max_length=150)),
                ('mineral_unit', models.CharField(choices=[('mg', 'miligram'), ('μg', 'mikrogram')], max_length=10)),
                ('mineral_recomended_consuption', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name': 'Minerał',
                'verbose_name_plural': 'Minerały',
            },
        ),
    ]
