# Generated by Django 3.0.2 on 2020-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='mineral_recomended_consuption',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
