# Generated by Django 3.0.2 on 2020-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitamin_name', models.CharField(max_length=150)),
                ('vitamin_unit', models.CharField(choices=[('mg', 'miligram'), ('μg', 'mikrogram')], max_length=2)),
                ('vitamin_recomended_consuption', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name': 'Witaminy',
                'verbose_name_plural': 'Witaminy',
            },
        ),
    ]
