# Generated by Django 3.0.2 on 2020-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitamin',
            options={'verbose_name': 'Witamina', 'verbose_name_plural': 'Witaminy'},
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='vitamin_unit',
            field=models.CharField(choices=[('mg', 'miligram'), ('μg', 'mikrogram')], max_length=10),
        ),
    ]
