# Generated by Django 3.0.2 on 2020-01-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamins', '0002_auto_20200128_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='vitamin_symbol',
            field=models.CharField(default='Witamina', max_length=100),
        ),
    ]
