# Generated by Django 3.0.2 on 2020-01-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamins', '0004_auto_20200129_0930'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueVit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitamins.Vitamin')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_vitamin',
            field=models.ManyToManyField(through='products.ValueVit', to='vitamins.Vitamin'),
        ),
    ]
