# Generated by Django 3.0.2 on 2020-02-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200129_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuevit',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
